[ui]
is_visible = 1
label = Splunk React App
supported_themes = light, dark

[launcher]
author = Your Team
description = React application template for Splunk
version = 0.1.0

[package]
check_for_updates = 0
id = conf2026

[install]
is_configured = 0
build = 1

[id]
name = conf2026
version = 0.1.0
