[butterfly_journal]
field.commonName = string
field.scientificName = string
field.family = string
field.collected = bool
field.priority = bool
field.primaryColor = string
field.secondaryColor = string
field.notes = string

